export const PROJECTS = [
  // {
  //   id: 1,
  //   name: "Palindrome Checker",
  //   imgSrc:
  //     "https://res.cloudinary.com/devsteveserver/image/upload/v1658972277/pow_iibcpq.png",
  //   desc: "Check for Palindromes",
  //   siteLink: "https://palindromcheck.netlify.app/",
  // },
  // {
  //   id: 2,
  //   name: "WeDo!",
  //   imgSrc:
  //     "https://res.cloudinary.com/devsteveserver/image/upload/v1659632883/proof_f7kc8c.png",
  //   desc: "A To-Do List App",
  //   siteLink: "https://wedoo.netlify.app/",
  // },
  // {
  //   id: 3,
  //   name: "Rock-Paper-Scissors",
  //   imgSrc:
  //     "https://res.cloudinary.com/devsteveserver/image/upload/v1667340301/powrps_mooiwz.png",
  //   desc: "A Rock-Paper-Scissors Game",
  //   siteLink: "https://rpsgamex.netlify.app/",
  // },
  {
    id: 6,
    name: "Bryllupslisten",
    imgSrc: "/bryllup.png",
    desc: "Ecommerce site",
    siteLink: "https://bryllupslisten.no/",
    techStack: ["NextJS", "TailwindCSS", "Firebase"],
  },
  {
    id: 7,
    name: "Macel Care Limited",
    imgSrc: "/marcel.png",
    desc: "Health Care website",
    siteLink: "https://macelcare.com/",
    techStack: ["NextJS", "TailwindCSS", "Firebase"],
  },
  {
    id: 3,
    name: "Openwaver Company Limited",
    imgSrc: "/openwaver.png",
    desc: "Openwaver company website",
    siteLink: "https://openwaver.com/",
    techStack: ["NextJS", "TailwindCSS"],
  },
  {
    id: 1,
    name: "Trailers Home",
    imgSrc: "/palmflix.png",
    desc: "Movie App with Trailers",
    siteLink: "https://palmflix.vercel.app/",
    techStack: ["NextJS", "Firebase", "TailwindCSS", "ContextAPI"],
  },
  {
    id: 2,
    name: "Palmplayy",
    imgSrc: "/palmplayy.png",
    desc: "Music App with Shazam API",
    siteLink: "https://palmplayy.vercel.app/",
    techStack: ["NextJS", "NextAuth", "TailwindCSS", "Redux"],
  },

  {
    id: 5,
    name: "Palmstore",
    imgSrc: "/palmstore1.png",
    desc: "Twitter and showwcase thread to images",
    siteLink: "https://palmstore .vercel.app/",
    techStack: ["NextJS", "TailwindCSS"],
  },
  {
    id: 3,
    name: "Be-Little",
    imgSrc: "/belittle.png",
    desc: "Image Compression App",
    siteLink: "https://be-little.vercel.app/",
    techStack: ["NextJS", "TailwindCSS"],
  },

  {
    id: 8,
    name: "Waverpass",
    imgSrc: "/waverpass.png",
    desc: "Waverpass Mint page",
    siteLink: "https://www.waverpass.com/",
    techStack: ["NextJS", "TailwindCSS", "Firebase"],
  },
  {
    id: 9,
    name: "Magna",
    imgSrc: "/magna.webp",
    desc: "NFT Project Landing Page",
    siteLink: "https://www.buymagna.com/",
    techStack: ["NextJS", "TailwindCSS", "Firebase"],
  },
  {
    id: 4,
    name: "Snap-A-Shot",
    imgSrc: "/snapashot.png",
    desc: "Twitter and showwcase thread to images",
    siteLink: "https://snap-a-shot.vercel.app/",
    techStack: ["NextJS", "TailwindCSS", "Zustand"],
  },
];
