import Header from '@/components/Header'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-[#222] text-white">
        <div className="relative scroll-smooth select-none">
          <Header />
          <section className="max-w-7xl min-h-[70vh] px-4 mx-auto">
            {children}
          </section>
          <Footer />
        </div>
      </body>
    </html>
  )
}
